services:
  qr-linker:
    build: .
    container_name: qr-linker
    restart: unless-stopped
    environment:
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      - PORT=8080
      - DB_PATH=${DB_PATH:-/app/data/urls.db}
    volumes:
      - qr_linker_data:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qr-linker.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.qr-linker.entrypoints=websecure"
      - "traefik.http.routers.qr-linker.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.services.qr-linker.loadbalancer.server.port=8080"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/login",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qr_linker_data:
    driver: local

networks:
  traefik:
    external: true
